[package]
name = "bewu"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.68"
async-rusqlite = { git = "https://github.com/ThatAnnoyingKid/pikadick-rs", features = [ "bundled" ] }
axum = "0.6.4"
fd-lock = "3.0.9"
kitsu = { path = "../lib/kitsu-rs", features = [ "rustls-tls" ], default-features = false }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.24.2", features = [ "rt", "rt-multi-thread", "signal", "macros" ] }
toml = "0.7.0"
tower = "0.4.13"
tower-http = { version = "0.3.5", features = [ "fs", "trace" ] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
vidstreaming = { path = "../lib/vidstreaming-rs", features = [ "rustls-tls" ], default-features = false }
