[package]
name = "bewu"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.68"
axum = "0.6.1"
tokio = { version = "1.23.0", features = [ "rt", "rt-multi-thread", "signal" ] }
tower = "0.4.13"
tower-http = { version = "0.3.5", features = [ "fs", "trace" ] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
