bind-address = "<server bind address>"
public-directory = "<public assets directory>"
data-directory = "<data directory>"

[logging]
include-headers = <true/false, whether to log headers>
directives = <a list of logging directives>